app_homepage:
    path: /
    controller: App\Controller\HomeController::index


app_calendar:
    path: /calendar
    controller: App\Controller\CalendarController::index


save_appointment:
    path: /save-appointment
    controller: App\Controller\AppointmentController::save
    methods: POST


appointment_success:
    path: /appointment-success
    controller: App\Controller\AppointmentController::success